#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from sys import exit
from ufoLib2 import Font
from argparse import ArgumentParser

parser = ArgumentParser(description='Move (translate) a named anchor in all UFO glyphs that have it')
parser.add_argument('FILE_NAME', help='UFO path')
parser.add_argument('anchor_name', help='Anchor name')
parser.add_argument('deltaX', help='Delta-X', type=float)
parser.add_argument('deltaY', help='Delta-Y', type=float)

args = parser.parse_args()

if args.deltaX == 0 and args.deltaY == 0:
  print('Nothing to do here. Exiting.')
  exit()

font = Font.open(args.FILE_NAME)
updateCount = 0;
anchor_names = [args.anchor_name, '_' + args.anchor_name]
for glyph in font:
  for anchor in glyph.anchors:
    if anchor.name in (anchor_names):
      anchor.x += args.deltaX
      anchor.y += args.deltaY
      updateCount += 1

font.save()
print(f'Done. Made {updateCount} changes.')
